version: '3.8'

services:
  # Development version with hot reload
  user-management-api-dev:
    build: 
      context: .
      target: production
    container_name: user_management_api_dev
    restart: unless-stopped
    environment:
      - SECRET_KEY=dev-secret-key-not-for-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=sqlite:///./data/user_management_dev.db
      - BCRYPT_ROUNDS=4  # Faster for development
      - ENCRYPTION_KEY=dev-encryption-key-32-bytes-long
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123!
      - ENABLE_IP_WHITELIST=false
      - WHITELISTED_IPS=127.0.0.1,localhost
      - RATE_LIMIT_PER_MINUTE=120  # Higher for development
      - BATCH_LOG_INTERVAL_MINUTES=5
      - MEMORY_THRESHOLD_MB=50
      - APP_NAME=User Management API (Dev)
      - APP_VERSION=1.0.0-dev
      - DEBUG=true
      - REDIS_URL=redis://redis-dev:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount source code for development
      - dev_data:/app/data
      - dev_logs:/app/logs
    depends_on:
      - redis-dev
    networks:
      - user_management_dev_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: user_management_redis_dev
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"  # Expose Redis port for development
    volumes:
      - redis_dev_data:/data
    networks:
      - user_management_dev_network

volumes:
  dev_data:
    driver: local
  dev_logs:
    driver: local
  redis_dev_data:
    driver: local

networks:
  user_management_dev_network:
    driver: bridge